PENTAHO_SERVER_IP=10.80.230.193
PENTAHO_SERVER_USERNAME=admin
PENTAHO_SERVER_PASSWORD=password
BIDB_HOST=10.80.230.246
BIDB_DB_NAME=bidb
BIDB_PORT=5432
BIDB_USERNAME=bidb_ro
BIDB_PASSWORD=4aU94t8v+4d+W
BIDB_SCHEMA_NAME=bidb
BIDB_EXT_HOST=airlinesample.cyj079bqebpx.us-west-2.rds.amazonaws.com
BIDB_EXT_DB_NAME=postgres
BIDB_EXT_PORT=5432
BIDB_EXT_USERNAME=postgres
BIDB_EXT_PASSWORD=Password1
BIDB_EXT_SCHEMA_NAME=bidb_ext_dev
PDC_HOST=http://10.80.230.246
PDC_USERNAME=admin
PDC_PASSWORD=Welcome123!
PDC_LINEAGE_PAGE_SIZE=100