apiVersion: v1
kind: Namespace
metadata:
  name: pentaho-server
  labels:
    name: pentaho-server
    app.kubernetes.io/name: pentaho-server
    app.kubernetes.io/instance: pentaho-server
    app.kubernetes.io/version: "11.0.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: pentaho-platform
    app.kubernetes.io/managed-by: kubectl
